name: Convert Markdown Videos

on:
 push:
    branches:
      - main

jobs:
 convert_videos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If your script requires any dependencies, install them here

    - name: Convert Markdown videos to HTML
      run: python adjust-video-tag.py content/docs/AprendendoAWS
