name: Convert Markdown Videos

on:
 push:
    branches:
      - main
jobs:
 convert_videos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Convert Markdown videos to HTML
      run: python adjust-video-tag.py content/docs/AprendendoAWS

    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add content/docs/AprendendoAWS
        git commit -m "Update Markdown videos" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: main
      

      
